cats/config/routes.rb
Cats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, :only => [:edit, :update, :destroy, :create, :new] do
    member do
      put 'approve'
      put 'deny'
    end
  end
end

cats/app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :name, :age, :birth_date, :color, :sex

  validates :name, :age, :birth_date, :color, :sex, :presence => true
  validates :color, :inclusion => {in: %w(red green blue),
    message: "%{value} is not a valid color"}
  validates :sex, :inclusion => {in: %w(M F),
    message: "%{value} is not a valid sex"}

  has_many :rental_requests,
    :primary_key => :id,
    :foreign_key => :cat_id,
    :class_name => "CatRentalRequest",
    :dependent => :destroy
end

cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date

  before_validation(on: :create) do
    self.status = "PENDING"
  end

  validates :cat_id, :start_date, :end_date, :status, :presence => true

  validates :status, :inclusion => {in: %w(PENDING APPROVED DENIED),
    message: "%{value} is not a valid status"}

  validate :overlapping_approved_requests, on: :create

  belongs_to :cat,
    :primary_key => :id,
    :foreign_key => :cat_id,
    :class_name => "Cat"

  def overlapping_requests?(requests)
    return false if requests.first.nil?
    requests.sort_by! { |request| request.start_date}
    (requests.count-2).times do |t|
      if requests[t].end_date > requests[t+1].start_date
        return true
      end
    end
    false
  end

  def overlapping_approved_requests
    requests = self.cat.rental_requests.map do |request|
      request if request.status == "APPROVED"
    end

    errors.add(:overlap, "That's an overlapping request!!") if overlapping_requests?(requests)
  end

  def approve!
    self.status = "APPROVED"
    self.save!
    overlapping_pending_requests
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def overlapping_pending_requests
    requests = self.cat.rental_requests.map do |request|
      request if request.status == "PENDING"
    end
    requests.delete(nil)
    p requests
    deny = requests.select { |request| request.end_date > self.start_date or request.start_date < self.end_date }
    CatRentalRequest.transaction do
      deny.each do |req|
        req.status = "DENIED"
        req.save!
      end
    end
  end
end

cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
end

cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @request = CatRentalRequest.new

    render :new
  end

  def create
    params[:request][:cat_id] = params[:cat]
    @request = CatRentalRequest.new(params[:request])
    if @request.save
      redirect_to cat_url(@request.cat)
    else
      render :new
    end
  end

  def edit
    @request = CatRentalRequest.find(params[:id])
    render :edit
  end

  def update
    @request = CatRentalRequest.find(params[:id])
    raise "you can't edit an unexisting request!" unless @request.persisted?
    if @request.update_attributes(params[:request])
      redirect_to cat_url(@request.cat)
    else
      render :edit
    end
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_url(@request.cat)
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_url(@request.cat)
  end
end

cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def new
    @cat = Cat.new

    render :new
  end

  def create
    @cat = Cat.new(params[:cat])
    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    raise "you can't edit an unexisting cat!" unless @cat.persisted?
    if @cat.update_attributes(params[:cat])
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end
end

cats/app/helpers/application_helper.rb
module ApplicationHelper
end

cats/app/helpers/cat_rental_requests_controller_helper.rb
module CatRentalRequestsControllerHelper
end

cats/app/views/cat_rental_requests/_form.html.erb
<% action_url = (action == :new) ? cat_rental_requests_url : cat_rental_request_url(@request) %>

<form action="<%= action_url %>" method="post">
	<% if action == :edit %>
		<input type="hidden" name="_method" value="put">
	<% end %>

	<label for="cat">Cat: </label>
	<select name="cat" id="cat">
		<% Cat.all.each do |cat| %>
			<option value="<%= cat.id %>"><%= cat.name %></option>
		<% end %>
	</select>
	<br>

  <label for="request_start_date">Start Date: </label>
	<input type="date" name="request[start_date]" id="request_start_date" value="<%= @request.start_date %>"><br>

  <label for="request_end_date">End Date: </label>
	<input type="date" name="request[end_date]" id="request_end_date" value="<%= @request.end_date %>"><br>

	<input type="submit" value="Request Cat!">
</form>

cats/app/views/cat_rental_requests/edit.html.erb
<%= render "form", :request => @request, :action => :edit %>

cats/app/views/cat_rental_requests/new.html.erb
<%= render "form", :request => @request, :action => :new %>

cats/app/views/cats/_form.html.erb
<% action_url = (action == :new) ? cats_url : cat_url(@cat) %>

<form action="<% action_url %>" method="post">
	<% if action == :edit %>
		<input type="hidden" name="_method" value="put">
	<% end %>

	<label for="cat_name">Name: </label>
	<input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>"><br>

	<label for="cat_age">Age: </label>
	<input type="text" name="cat[age]" id="cat_age" value="<%= @cat.age %>"><br>

	<% if @cat.sex == 'M' %>
	<% 	male = "checked='checked'" %>
	<% elsif @cat.sex == 'F' %>
	<% 	female = "checked='checked'" %>
	<% end %>

	<label for="cat_sex_female">Female: </label>
	<input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "#{female}" %>>
	<label for="cat_sex_male">Male: </label>
	<input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= "#{male}" %> ><br>

	<% if @cat.color == 'red' %>
	<% 	red = "selected" %>
	<% elsif @cat.color == 'blue' %>
	<% 	blue = "selected" %>
	<% elsif @cat.color == 'green' %>
	<% 	green = "selected" %>
	<% end %>

	<label for="cat_color">Color: </label>
	<select name="cat[color]" id="cat_color">
		<option value="red" <%= red %>>Red</option>
		<option value="blue" <%= blue %>>Blue</option>
		<option value="green" <%= green %>>Green</option>
	</select>
	<br>

  <label for="cat_birth_date">Birth Date: </label>
	<input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= @cat.birth_date %>"><br>

	<input type="submit" value="Submit Cat!">
</form>

cats/app/views/cats/edit.html.erb
<%= render "form", :cat => @cat, :action => :edit %>

cats/app/views/cats/index.html.erb
<table border="1">
	<th>Cats</th>
	<%@cats.each do |cat|%>
	<tr>
		<td><%=cat.name%></td>
		<td><%=cat.color%></td>
		<td><%=cat.age%></td>
	</tr>
	<%end%>
</table>

cats/app/views/cats/new.html.erb
<%= render "form", :cat => @cat, :action => :new %>

cats/app/views/cats/show.html.erb
<table border="1">
	<th><%= @cat.name %></th>
	<tr>
		<td><%= "Color: " + @cat.color.to_s %></td>
		<td><%= "Age: " + @cat.age.to_s %></td>
	</tr>
</table>
<h2>Requests</h2>
<% @cat.rental_requests.each do |request| %>
	<%= "Start Date: " + request.start_date.to_s %><br>
	<%= "End Date: " + request.end_date.to_s %><br>
	<%= "Status: " + request.status.to_s %><br>
	<%= button_to "Approve Request", approve_cat_rental_request_url(request), :method => :put %>
	<%= button_to "Deny Request", deny_cat_rental_request_url(request), :method => :put%>
<% end %>

cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>